#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get a list of staged files
STAGED_FILES=$(git diff --cached --name-only)

# Check if any staged files are in src/ or tests/
if echo "$STAGED_FILES" | grep -q -E "^(src|tests)/"; then
  echo "Running tests because files in src/ or tests/ were changed."
  npm test
else
  echo "No changes in src/ or tests/ directories. Skipping tests."
fi
